services:
  - type: web
    name: ctm-cabapua
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 60 --preload
    healthCheckPath: /login
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ctm-cabapua-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SURVEYHEART_API_TOKEN
        value: ""
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""

databases:
  - name: ctm-cabapua-db
    plan: free
    region: oregon
    databaseName: ctm_cabapua
    user: ctm_admin
